// src/components/Nav.svelte
<script>
	export let slug;

	function handleClick(event) {
		const url = event.target.getAttribute('href');
		document.querySelector(`article#${url}`).scrollIntoView();
	}
</script>

<style type="text/scss">
	@import "../styles/var.scss";
	nav {
		display: flex;
		flex-direction: column;
		align-items: flex-end;
		position: fixed;
		top: $pad;
		right: $pad;
		opacity: 0;
		transition: opacity 250ms;

		&.show {
			opacity: 1;
		}

		ul {

			&.nav-items {
				margin-bottom: $pad * 0.2;

				li {
					margin-right: $pad / 2;

					&:last-child {
						margin-right: 0;
					}
				}
			}

			&.lang-select {

				li:first-child {
					&:after {
						content: "\00a0/";
					}
				}
			}

			li {
				display: inline-block;

				&.active {

					a, button {
						
						&:after {
							transform: scale(1);
							opacity: 1;
						}
					}
				}

				a, button {
					position: relative;
					text-decoration: none;
					color: inherit;

					&:after {
						content: "";
						position: absolute;
						left: 0px;
						bottom: -$pad * 0.2;
						width: 100%;
						height: $pad * 0.1;
						background-color: $black;
						transform: scale(0.75);
						opacity: 0;
						transition: all 125ms;
					}
				}
			}
		}

		button {
			cursor: pointer;
		}
	}
</style>

<nav class="font-main font-small font-bold {$slug ? ' show' : ''}">
	<ul class="nav-items">
		<li class="{$slug === 'services' ? 'active' : ''}">
			<a on:click|preventDefault={handleClick} aria-current="{$slug === 'services' ? 'page' : undefined}" href="services">Services</a>
		</li>
		<li class="{$slug === 'work' ? 'active' : ''}">
			<a on:click|preventDefault={handleClick} aria-current="{$slug === 'work' ? 'page' : undefined}" href="work">Work</a>
		</li>
		<li class="{$slug === 'profile' ? 'active' : ''}">
			<a on:click|preventDefault={handleClick} aria-current="{$slug === 'profile' ? 'page' : undefined}" href="profile">Profile</a>
		</li>
		<li class="{$slug === 'contact' ? 'active' : ''}">
			<a on:click|preventDefault={handleClick} aria-current="{$slug === 'contact' ? 'page' : undefined}" href="contact">Contact</a>
		</li>
	</ul>
	<ul class="lang-select">
		<li><button>DE</button></li>
		<li><button>EN</button></li>
	</ul>
</nav>

// components/Nav.vue
<template>
  <nav>
    <ul>
      <li>
        <a
          href="#services"
          :class="{ active: activeEntry === 'services' }"
          @click.prevent="onClick"
        >
          Services
        </a>
      </li>
      <li>
        <a
          href="#projects"
          :class="{ active: activeEntry === 'projects' }"
          @click.prevent="onClick"
        >
          Projekte
        </a>
      </li>
      <li>
        <a
          href="#profile"
          :class="{ active: activeEntry === 'profile' }"
          @click.prevent="onClick"
        >
          Profil
        </a>
      </li>
      <li>
        <a
          href="#contact"
          :class="{ active: activeEntry === 'contact' }"
          @click.prevent="onClick"
        >
          Kontakt
        </a>
      </li>
    </ul>
  </nav>
</template>

<script>
export default {
  name: 'Nav',
  props: {
    activeEntry: {
      type: String,
      default: '',
    },
    headroom: {
      type: Object,
      default: () => {},
    },
  },
  methods: {
    onClick(event) {
      this.headroom?.freeze()
      const element = document.querySelector(event.target.getAttribute('href'))
      element.scrollIntoView({ block: 'start', inline: 'nearest' })
      setTimeout(() => this.headroom.unfreeze(), 250)
    },
  },
}
</script>

<style lang="scss" scoped>
nav {
  transition: opacity 250ms 0ms, transform 250ms 0ms;
  @media (min-width: $bp-2) {
    transition: opacity 250ms 250ms, transform 250ms 250ms;
  }
  ul {
    display: flex;
    flex-direction: column;
    align-items: flex-end;
    list-style: none;
    padding: 0;
    @media (min-width: $bp-2) {
      flex-direction: row;
      align-items: unset;
    }
    li {
      a {
        color: $grey;
        @media (min-width: $bp-2) {
          color: $black;
        }
        @extend %t-1;
        @extend %underline;

        position: relative;
        &::after {
          opacity: 0;
          transform: scaleX(0);
        }
        &.active {
          color: $black;
          &::after {
            transform: scaleX(1);
            opacity: 1;
          }
        }
      }
      &:not(:last-child) {
        @media (min-width: $bp-2) {
          margin: 0 $pad * 2 0 0;
        }
      }
    }
  }
}
</style>
